//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evbg.CC.Driver.SpotterGlobal.Radar.ServerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseResult", Namespace="http://schemas.datacontract.org/2004/07/Evbg.CC.Driver.GenericSimulator")]
    [System.SerializableAttribute()]
    public partial class ResponseResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Evbg.CC.Driver.SpotterGlobal.Radar.ServerService.ResultType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Evbg.CC.Driver.SpotterGlobal.Radar.ServerService.ResultType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultType", Namespace="http://schemas.datacontract.org/2004/07/Evbg.CC.Driver.GenericSimulator")]
    public enum ResultType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericDeviceInfo", Namespace="http://schemas.datacontract.org/2004/07/Evbg.CC.Driver.GenericSimulator.Configura" +
        "tion")]
    [System.SerializableAttribute()]
    public partial class GenericDeviceInfo : Evbg.CC.Driver.SpotterGlobal.Radar.ServerService.GenericAssetInfo {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTamperField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTamper {
            get {
                return this.IsTamperField;
            }
            set {
                if ((this.IsTamperField.Equals(value) != true)) {
                    this.IsTamperField = value;
                    this.RaisePropertyChanged("IsTamper");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericAssetInfo", Namespace="http://schemas.datacontract.org/2004/07/Evbg.CC.Driver.GenericSimulator.Configura" +
        "tion")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Evbg.CC.Driver.SpotterGlobal.Radar.ServerService.GenericDeviceInfo))]
    public partial class GenericAssetInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentID {
            get {
                return this.ParentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentIDField, value) != true)) {
                    this.ParentIDField = value;
                    this.RaisePropertyChanged("ParentID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericEvent", Namespace="http://schemas.datacontract.org/2004/07/Evbg.CC.Driver.GenericSimulator")]
    [System.SerializableAttribute()]
    public partial class GenericEvent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Evbg.CC.Driver.SpotterGlobal.Radar.ServerService.GenericAssetType AssetTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Evbg.CC.Driver.SpotterGlobal.Radar.ServerService.GeoSpatialEventData GeoSpatialEventDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ServerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimestampUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Evbg.CC.Driver.SpotterGlobal.Radar.ServerService.GenericEventType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Evbg.CC.Driver.SpotterGlobal.Radar.ServerService.GenericAssetType AssetType {
            get {
                return this.AssetTypeField;
            }
            set {
                if ((this.AssetTypeField.Equals(value) != true)) {
                    this.AssetTypeField = value;
                    this.RaisePropertyChanged("AssetType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceId {
            get {
                return this.DeviceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceIdField, value) != true)) {
                    this.DeviceIdField = value;
                    this.RaisePropertyChanged("DeviceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Evbg.CC.Driver.SpotterGlobal.Radar.ServerService.GeoSpatialEventData GeoSpatialEventData {
            get {
                return this.GeoSpatialEventDataField;
            }
            set {
                if ((object.ReferenceEquals(this.GeoSpatialEventDataField, value) != true)) {
                    this.GeoSpatialEventDataField = value;
                    this.RaisePropertyChanged("GeoSpatialEventData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ServerId {
            get {
                return this.ServerIdField;
            }
            set {
                if ((this.ServerIdField.Equals(value) != true)) {
                    this.ServerIdField = value;
                    this.RaisePropertyChanged("ServerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimestampUtc {
            get {
                return this.TimestampUtcField;
            }
            set {
                if ((this.TimestampUtcField.Equals(value) != true)) {
                    this.TimestampUtcField = value;
                    this.RaisePropertyChanged("TimestampUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Evbg.CC.Driver.SpotterGlobal.Radar.ServerService.GenericEventType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeoSpatialEventData", Namespace="http://schemas.datacontract.org/2004/07/Evbg.CC.Driver.GenericSimulator")]
    [System.SerializableAttribute()]
    public partial class GeoSpatialEventData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> AltitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> LongitudeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Altitude {
            get {
                return this.AltitudeField;
            }
            set {
                if ((this.AltitudeField.Equals(value) != true)) {
                    this.AltitudeField = value;
                    this.RaisePropertyChanged("Altitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericAssetType", Namespace="http://schemas.datacontract.org/2004/07/Evbg.CC.Driver.GenericSimulator")]
    public enum GenericAssetType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Server = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Device = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericEventType", Namespace="http://schemas.datacontract.org/2004/07/Evbg.CC.Driver.GenericSimulator")]
    public enum GenericEventType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GenericEvent = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TamperStart = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TamperEnd = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServerService.IServerService")]
    public interface IServerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/Login", ReplyAction="http://tempuri.org/IServerService/LoginResponse")]
        Evbg.CC.Driver.SpotterGlobal.Radar.ServerService.ResponseResult Login(string ip, int port, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/Login", ReplyAction="http://tempuri.org/IServerService/LoginResponse")]
        System.Threading.Tasks.Task<Evbg.CC.Driver.SpotterGlobal.Radar.ServerService.ResponseResult> LoginAsync(string ip, int port, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/Logout", ReplyAction="http://tempuri.org/IServerService/LogoutResponse")]
        bool Logout();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/Logout", ReplyAction="http://tempuri.org/IServerService/LogoutResponse")]
        System.Threading.Tasks.Task<bool> LogoutAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/GetDevices", ReplyAction="http://tempuri.org/IServerService/GetDevicesResponse")]
        Evbg.CC.Driver.SpotterGlobal.Radar.ServerService.GenericDeviceInfo[] GetDevices();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/GetDevices", ReplyAction="http://tempuri.org/IServerService/GetDevicesResponse")]
        System.Threading.Tasks.Task<Evbg.CC.Driver.SpotterGlobal.Radar.ServerService.GenericDeviceInfo[]> GetDevicesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/GetDevice", ReplyAction="http://tempuri.org/IServerService/GetDeviceResponse")]
        Evbg.CC.Driver.SpotterGlobal.Radar.ServerService.GenericDeviceInfo GetDevice(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/GetDevice", ReplyAction="http://tempuri.org/IServerService/GetDeviceResponse")]
        System.Threading.Tasks.Task<Evbg.CC.Driver.SpotterGlobal.Radar.ServerService.GenericDeviceInfo> GetDeviceAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/GetEvents", ReplyAction="http://tempuri.org/IServerService/GetEventsResponse")]
        Evbg.CC.Driver.SpotterGlobal.Radar.ServerService.GenericEvent[] GetEvents(System.DateTime startTimeUtc, System.DateTime endTimeUtc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/GetEvents", ReplyAction="http://tempuri.org/IServerService/GetEventsResponse")]
        System.Threading.Tasks.Task<Evbg.CC.Driver.SpotterGlobal.Radar.ServerService.GenericEvent[]> GetEventsAsync(System.DateTime startTimeUtc, System.DateTime endTimeUtc);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServerServiceChannel : Evbg.CC.Driver.SpotterGlobal.Radar.ServerService.IServerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServerServiceClient : System.ServiceModel.ClientBase<Evbg.CC.Driver.SpotterGlobal.Radar.ServerService.IServerService>, Evbg.CC.Driver.SpotterGlobal.Radar.ServerService.IServerService {
        
        public ServerServiceClient() {
        }
        
        public ServerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Evbg.CC.Driver.SpotterGlobal.Radar.ServerService.ResponseResult Login(string ip, int port, string username, string password) {
            return base.Channel.Login(ip, port, username, password);
        }
        
        public System.Threading.Tasks.Task<Evbg.CC.Driver.SpotterGlobal.Radar.ServerService.ResponseResult> LoginAsync(string ip, int port, string username, string password) {
            return base.Channel.LoginAsync(ip, port, username, password);
        }
        
        public bool Logout() {
            return base.Channel.Logout();
        }
        
        public System.Threading.Tasks.Task<bool> LogoutAsync() {
            return base.Channel.LogoutAsync();
        }
        
        public Evbg.CC.Driver.SpotterGlobal.Radar.ServerService.GenericDeviceInfo[] GetDevices() {
            return base.Channel.GetDevices();
        }
        
        public System.Threading.Tasks.Task<Evbg.CC.Driver.SpotterGlobal.Radar.ServerService.GenericDeviceInfo[]> GetDevicesAsync() {
            return base.Channel.GetDevicesAsync();
        }
        
        public Evbg.CC.Driver.SpotterGlobal.Radar.ServerService.GenericDeviceInfo GetDevice(string id) {
            return base.Channel.GetDevice(id);
        }
        
        public System.Threading.Tasks.Task<Evbg.CC.Driver.SpotterGlobal.Radar.ServerService.GenericDeviceInfo> GetDeviceAsync(string id) {
            return base.Channel.GetDeviceAsync(id);
        }
        
        public Evbg.CC.Driver.SpotterGlobal.Radar.ServerService.GenericEvent[] GetEvents(System.DateTime startTimeUtc, System.DateTime endTimeUtc) {
            return base.Channel.GetEvents(startTimeUtc, endTimeUtc);
        }
        
        public System.Threading.Tasks.Task<Evbg.CC.Driver.SpotterGlobal.Radar.ServerService.GenericEvent[]> GetEventsAsync(System.DateTime startTimeUtc, System.DateTime endTimeUtc) {
            return base.Channel.GetEventsAsync(startTimeUtc, endTimeUtc);
        }
    }
}
