
//******************************************************************************
//*																			   *
//*																			   *
//*																			   *
//*  DO NOT MODIFY THIS FILE - IT IS AUTOGENERATED FROM THE CONNECTOR DIAGRAM  *
//*																			   *
//*																			   *
//*																			   *
//******************************************************************************

using System;
using System.Drawing;
using System.ServiceModel;
using System.Windows.Forms;
using System.Diagnostics.CodeAnalysis;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Threading.Tasks;
using CNL.IPSecurityCenter.Driver;
using CNL.IPSecurityCenter.Driver.Attributes;
using CNL.IPSecurityCenter.Driver.ServiceLocation;
using CNL.IPSecurityCenter.Driver.Video;
using CNL.IPSecurityCenter.Driver.Video.DeviceConnection;
using CNL.IPSecurityCenter.Driver.Video.Playback;
using CNL.IPSecurityCenter.Driver.Video.Export;
using CNL.IPSecurityCenter.Driver.Ptz;
using CNL.IPSecurityCenter.Driver.Attributes.Validation;
using VideoDeviceInterfaceDescriptor = CNL.IPSecurityCenter.Driver.Video.DeviceConnection.DeviceInterfaceDescriptor;
using CNL.IPSecurityCenter.Driver.Types.GeoSpatial;


namespace Evbg.CC.Driver.SpotterGlobal.Radar
{
	[GeneratedCode("Driver.Design", "1.0.0.0")]
	[Serializable]
    [ServiceBehaviorAttribute(InstanceContextMode = InstanceContextMode.Single)]
	public abstract class RadarServerBase : Device , IDisposable     {
		// -- constructors

		/// <summary>
        /// Initializes a new instance of the <see cref="RadarServerBase"/> class.
        /// </summary>
        protected RadarServerBase()
        {
        }

		// -- fields

		[NonSerialized]
		private bool disposed;

        // -- events	

		//Event declarations
		/// <summary>
/// Generic Server Event
/// </summary>
[field: NonSerialized]
		[CategoryEvents]
		public event EventHandler<ServerEventEventArgs> ServerEventEvent;

        // -- properties	

		//Network device
        public virtual TimeSpan RetryInterval { get; set; }
        public virtual TimeSpan Timeout { get; set; }
        public virtual string IP { get; set; }
        public virtual int Port { get; set; }

		/// <summary>
        /// Time interval in seconds between web service connectivity checks.
        /// </summary>
        public virtual int KeepAliveInterval { get; set; }
		/// <summary>
        /// Maximum devices allowed to populate at a time.
        /// </summary>
        public virtual int DevicePopulationBatchSize { get; set; }
		/// <summary>
        /// Logging level of the driver.
        /// </summary>
        public virtual CNL.IPSecurityCenter.Driver.Utility.Logging.LogLevel LogLevel { get; set; }
		/// <summary>
        /// Example Property for Server
        /// </summary>
        public virtual int ListnerPort { get; set; }
		/// <summary>
        /// When true, the connector simulates the subsystem instead of connecting to a real one.
        /// </summary>
        public virtual bool SimulationMode { get; set; }
		/// <summary>
        /// Time interval in miliseconds between web service connectivity checks.
        /// </summary>
        public virtual int PollingInterval { get; set; }

		// -- public methods

		public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

		//Network device
		public abstract void Connect();
        public abstract void Disconnect();
		
		

        /// <summary>
        /// Refresh the devices to match the current configuration on Generic server.
        /// </summary>
        public abstract bool RefreshDevices(
			bool refreshProperties
		);

        /// <summary>
        /// Sample Server Method
        /// </summary>
        public abstract void SampleServerMethod(
		);


        // -- protected methods


        protected virtual void Dispose(bool disposing)
        {
            if (!disposed)
            {
                if (disposing)
                {
                }

                disposed = true;
            }
        }
		
	

			
        /// <summary>
        /// Raises the ServerEventEvent event.
        /// </summary>
        internal virtual void OnServerEventEvent(ServerEventEventArgs e)
        {
            if(ServerEventEvent != null)
                ServerEventEvent.Invoke(this, e);
        }
        			
		    }
	[GeneratedCode("Driver.Design", "1.0.0.0")]
	[Serializable]
    [ServiceBehaviorAttribute(InstanceContextMode = InstanceContextMode.Single)]
	public abstract class RadarBase : Device , IDisposable     {
		// -- constructors

		/// <summary>
        /// Initializes a new instance of the <see cref="RadarBase"/> class.
        /// </summary>
        protected RadarBase()
        {
        }

		// -- fields

		[NonSerialized]
		private bool disposed;

        // -- events	

		//Event declarations
		/// <summary>
/// Generic Device Event
/// </summary>
[field: NonSerialized]
		[CategoryEvents]
		public event EventHandler<DeviceEventEventArgs> DeviceEventEvent;
		/// <summary>
/// Alarm Track Recieved
/// </summary>
[field: NonSerialized]
		[CategoryEvents]
		public event EventHandler<AlarmTrackRecievedEventArgs> AlarmTrackRecievedEvent;

		[field: NonSerialized]
        public event EventHandler<CustomStateChangedEventArgs> CustomStateChanged; 
        // -- properties	

		/// <summary>
        /// Unique identifier.
        /// </summary>
        public virtual string Id { get; set; }
		/// <summary>
        /// The parent device ID
        /// </summary>
        public virtual string ParentId { get; set; }
		/// <summary>
        /// Device Name
        /// </summary>
        public virtual string DeviceName { get; set; }

		// -- public methods

		public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }
		
		

        /// <summary>
        /// Get Device Details
        /// </summary>
        public abstract void GetDeviceDetails(
			string DeviceId
		);


        // -- protected methods

		// Custom States

		/// <summary>
        /// Raises the <see cref="CustomStateChanged"/> event.
        /// </summary>
        /// <param name="e">The event arguments for the event.</param>
        /// <remarks>
        /// This should be raised after the device has come online if the device needs to report a connected but abnormal condition.
        /// These states can be defined on the driver design surface, and a number of common ones are available in the 
        /// CNL.IPSecurityCenter.Driver.CustomStates namespace
        /// </remarks>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="e"/> is null.</exception>
        protected virtual void OnCustomStateChanged(CustomStateChangedEventArgs e)
        {
            if (e == null)
            {
                throw new ArgumentNullException("e");
            }

            if (CustomStateChanged != null)
            {
                CustomStateChanged.Invoke(this, e);
            }
        }

        /// <summary>
        /// Raises the <see cref="CustomStateChanged"/> event.
        /// </summary>
        /// <param name="state">The custom state for the device.</param>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="state"/> is null.</exception>
        protected void OnCustomStateChanged(ICustomState state)
        {
            if (state == null)
            {
                throw new ArgumentNullException("state");
            }

            OnCustomStateChanged(new CustomStateChangedEventArgs(Identifier, state));
        }

        /// <summary>
        /// Raises the <see cref="CustomStateChanged"/> event.
        /// </summary>
        /// <param name="state">The custom state for the device.</param>
        /// <param name="message">A message providing more information about the state.</param>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="state"/> is null.</exception>
        protected void OnCustomStateChanged(ICustomState state, string message)
        {
            if (state == null)
            {
                throw new ArgumentNullException("state");
            }

            OnCustomStateChanged(new CustomStateChangedEventArgs(Identifier, state, message));
        }

        /// <summary>
        /// Raises the <see cref="CustomStateChanged"/> event.
        /// </summary>
        /// <param name="deviceInterface">The device interface of the child device that should change state</param>
        /// <param name="state">The custom state for the device.</param>
        /// <remarks>
        /// This overload is used to change the state of a specific child device.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="state"/> is null.</exception>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="deviceInterface"/> is null.</exception>
        protected void OnCustomStateChanged(DeviceInterface deviceInterface, ICustomState state)
        {
            if (state == null)
            {
                throw new ArgumentNullException("state");
            }

            if (deviceInterface == null)
            {
                throw new ArgumentNullException("deviceInterface");
            }

            OnCustomStateChanged(new CustomStateChangedEventArgs(Identifier, deviceInterface.Identifier, state));
        }

        /// <summary>
        /// Raises the <see cref="CustomStateChanged"/> event.
        /// </summary>
        /// <param name="deviceInterface">The device interface of the child device that should change state</param>
        /// <param name="state">The custom state for the device.</param>
        /// <param name="message">A message providing more information about the state.</param>
        /// <remarks>
        /// This overload is used to change the state of a specific child device.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="state"/> is null.</exception>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="deviceInterface"/> is null.</exception>
        protected void OnCustomStateChanged(DeviceInterface deviceInterface, ICustomState state, string message)
        {
            if (state == null)
            {
                throw new ArgumentNullException("state");
            }

            if (deviceInterface == null)
            {
                throw new ArgumentNullException("deviceInterface");
            }

            OnCustomStateChanged(new CustomStateChangedEventArgs(Identifier, deviceInterface.Identifier, state, message));
        }


        protected virtual void Dispose(bool disposing)
        {
            if (!disposed)
            {
                if (disposing)
                {
                }

                disposed = true;
            }
        }
		
	

			
        /// <summary>
        /// Raises the DeviceEventEvent event.
        /// </summary>
        internal virtual void OnDeviceEventEvent(DeviceEventEventArgs e)
        {
            if(DeviceEventEvent != null)
                DeviceEventEvent.Invoke(this, e);
        }
        		
        /// <summary>
        /// Raises the AlarmTrackRecievedEvent event.
        /// </summary>
        internal virtual void OnAlarmTrackRecievedEvent(AlarmTrackRecievedEventArgs e)
        {
            if(AlarmTrackRecievedEvent != null)
                AlarmTrackRecievedEvent.Invoke(this, e);
        }
        			
		 
		#region IGeoSpatialAware implementation
		
		public virtual int SpatialReferenceIdentifier { get; set; }
		
		public virtual double Longitude { get; set; }
		
		public virtual double Latitude { get; set; }

		#endregion
  
		#region IGeoSpatialAwareWithAlt implementation
		
		public virtual Nullable<double> Altitude { get; set; }

		#endregion
     }
	[GeneratedCode("Driver.Design", "1.0.0.0")]
	[Serializable]
    [ServiceBehaviorAttribute(InstanceContextMode = InstanceContextMode.Single)]
	public abstract class ZoneBase : Device , IDisposable     {
		// -- constructors

		/// <summary>
        /// Initializes a new instance of the <see cref="ZoneBase"/> class.
        /// </summary>
        protected ZoneBase()
        {
        }

		// -- fields

		[NonSerialized]
		private bool disposed;

        // -- events	

		//Event declarations
		/// <summary>
/// Track Update
/// </summary>
[field: NonSerialized]
		[CategoryEvents]
		public event EventHandler<TrackUpdateEventArgs> TrackUpdateEvent;

		[field: NonSerialized]
        public event EventHandler<CustomStateChangedEventArgs> CustomStateChanged; 
        // -- properties	

		/// <summary>
        /// Unique identifier.
        /// </summary>
        public virtual string Id { get; set; }
		/// <summary>
        /// The parent device ID
        /// </summary>
        public virtual string ParentId { get; set; }
		/// <summary>
        /// Type String
        /// </summary>
        public virtual string TypeString { get; set; }
		/// <summary>
        /// Active
        /// </summary>
        public virtual string Active { get; set; }
		/// <summary>
        /// Device Name
        /// </summary>
        public virtual string DeviceName { get; set; }

		// -- public methods

		public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }
		
		


        // -- protected methods

		// Custom States

		/// <summary>
        /// Raises the <see cref="CustomStateChanged"/> event.
        /// </summary>
        /// <param name="e">The event arguments for the event.</param>
        /// <remarks>
        /// This should be raised after the device has come online if the device needs to report a connected but abnormal condition.
        /// These states can be defined on the driver design surface, and a number of common ones are available in the 
        /// CNL.IPSecurityCenter.Driver.CustomStates namespace
        /// </remarks>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="e"/> is null.</exception>
        protected virtual void OnCustomStateChanged(CustomStateChangedEventArgs e)
        {
            if (e == null)
            {
                throw new ArgumentNullException("e");
            }

            if (CustomStateChanged != null)
            {
                CustomStateChanged.Invoke(this, e);
            }
        }

        /// <summary>
        /// Raises the <see cref="CustomStateChanged"/> event.
        /// </summary>
        /// <param name="state">The custom state for the device.</param>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="state"/> is null.</exception>
        protected void OnCustomStateChanged(ICustomState state)
        {
            if (state == null)
            {
                throw new ArgumentNullException("state");
            }

            OnCustomStateChanged(new CustomStateChangedEventArgs(Identifier, state));
        }

        /// <summary>
        /// Raises the <see cref="CustomStateChanged"/> event.
        /// </summary>
        /// <param name="state">The custom state for the device.</param>
        /// <param name="message">A message providing more information about the state.</param>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="state"/> is null.</exception>
        protected void OnCustomStateChanged(ICustomState state, string message)
        {
            if (state == null)
            {
                throw new ArgumentNullException("state");
            }

            OnCustomStateChanged(new CustomStateChangedEventArgs(Identifier, state, message));
        }

        /// <summary>
        /// Raises the <see cref="CustomStateChanged"/> event.
        /// </summary>
        /// <param name="deviceInterface">The device interface of the child device that should change state</param>
        /// <param name="state">The custom state for the device.</param>
        /// <remarks>
        /// This overload is used to change the state of a specific child device.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="state"/> is null.</exception>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="deviceInterface"/> is null.</exception>
        protected void OnCustomStateChanged(DeviceInterface deviceInterface, ICustomState state)
        {
            if (state == null)
            {
                throw new ArgumentNullException("state");
            }

            if (deviceInterface == null)
            {
                throw new ArgumentNullException("deviceInterface");
            }

            OnCustomStateChanged(new CustomStateChangedEventArgs(Identifier, deviceInterface.Identifier, state));
        }

        /// <summary>
        /// Raises the <see cref="CustomStateChanged"/> event.
        /// </summary>
        /// <param name="deviceInterface">The device interface of the child device that should change state</param>
        /// <param name="state">The custom state for the device.</param>
        /// <param name="message">A message providing more information about the state.</param>
        /// <remarks>
        /// This overload is used to change the state of a specific child device.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="state"/> is null.</exception>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="deviceInterface"/> is null.</exception>
        protected void OnCustomStateChanged(DeviceInterface deviceInterface, ICustomState state, string message)
        {
            if (state == null)
            {
                throw new ArgumentNullException("state");
            }

            if (deviceInterface == null)
            {
                throw new ArgumentNullException("deviceInterface");
            }

            OnCustomStateChanged(new CustomStateChangedEventArgs(Identifier, deviceInterface.Identifier, state, message));
        }


        protected virtual void Dispose(bool disposing)
        {
            if (!disposed)
            {
                if (disposing)
                {
                }

                disposed = true;
            }
        }
		
	

			
        /// <summary>
        /// Raises the TrackUpdateEvent event.
        /// </summary>
        internal virtual void OnTrackUpdateEvent(TrackUpdateEventArgs e)
        {
            if(TrackUpdateEvent != null)
                TrackUpdateEvent.Invoke(this, e);
        }
        			
		 
		#region IGeoSpatialAwareWithAlt implementation
		
		public virtual Nullable<double> Altitude { get; set; }

		#endregion
  
		#region IGeoSpatialAware implementation
		
		public virtual int SpatialReferenceIdentifier { get; set; }
		
		public virtual double Longitude { get; set; }
		
		public virtual double Latitude { get; set; }

		#endregion
     }
	[GeneratedCode("Driver.Design", "1.0.0.0")]
	[Serializable]
    [ServiceBehaviorAttribute(InstanceContextMode = InstanceContextMode.Single)]
	public abstract class UDCBase : Device , IDisposable     {
		// -- constructors

		/// <summary>
        /// Initializes a new instance of the <see cref="UDCBase"/> class.
        /// </summary>
        protected UDCBase()
        {
        }

		// -- fields

		[NonSerialized]
		private bool disposed;

        // -- events	

		//Event declarations

		[field: NonSerialized]
        public event EventHandler<CustomStateChangedEventArgs> CustomStateChanged; 
        // -- properties	

		/// <summary>
        /// Unique identifier.
        /// </summary>
        public virtual string Id { get; set; }
		/// <summary>
        /// The parent device ID
        /// </summary>
        public virtual string ParentId { get; set; }
		/// <summary>
        /// Device Name
        /// </summary>
        public virtual string DeviceName { get; set; }

		// -- public methods

		public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }
		
		


        // -- protected methods

		// Custom States

		/// <summary>
        /// Raises the <see cref="CustomStateChanged"/> event.
        /// </summary>
        /// <param name="e">The event arguments for the event.</param>
        /// <remarks>
        /// This should be raised after the device has come online if the device needs to report a connected but abnormal condition.
        /// These states can be defined on the driver design surface, and a number of common ones are available in the 
        /// CNL.IPSecurityCenter.Driver.CustomStates namespace
        /// </remarks>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="e"/> is null.</exception>
        protected virtual void OnCustomStateChanged(CustomStateChangedEventArgs e)
        {
            if (e == null)
            {
                throw new ArgumentNullException("e");
            }

            if (CustomStateChanged != null)
            {
                CustomStateChanged.Invoke(this, e);
            }
        }

        /// <summary>
        /// Raises the <see cref="CustomStateChanged"/> event.
        /// </summary>
        /// <param name="state">The custom state for the device.</param>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="state"/> is null.</exception>
        protected void OnCustomStateChanged(ICustomState state)
        {
            if (state == null)
            {
                throw new ArgumentNullException("state");
            }

            OnCustomStateChanged(new CustomStateChangedEventArgs(Identifier, state));
        }

        /// <summary>
        /// Raises the <see cref="CustomStateChanged"/> event.
        /// </summary>
        /// <param name="state">The custom state for the device.</param>
        /// <param name="message">A message providing more information about the state.</param>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="state"/> is null.</exception>
        protected void OnCustomStateChanged(ICustomState state, string message)
        {
            if (state == null)
            {
                throw new ArgumentNullException("state");
            }

            OnCustomStateChanged(new CustomStateChangedEventArgs(Identifier, state, message));
        }

        /// <summary>
        /// Raises the <see cref="CustomStateChanged"/> event.
        /// </summary>
        /// <param name="deviceInterface">The device interface of the child device that should change state</param>
        /// <param name="state">The custom state for the device.</param>
        /// <remarks>
        /// This overload is used to change the state of a specific child device.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="state"/> is null.</exception>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="deviceInterface"/> is null.</exception>
        protected void OnCustomStateChanged(DeviceInterface deviceInterface, ICustomState state)
        {
            if (state == null)
            {
                throw new ArgumentNullException("state");
            }

            if (deviceInterface == null)
            {
                throw new ArgumentNullException("deviceInterface");
            }

            OnCustomStateChanged(new CustomStateChangedEventArgs(Identifier, deviceInterface.Identifier, state));
        }

        /// <summary>
        /// Raises the <see cref="CustomStateChanged"/> event.
        /// </summary>
        /// <param name="deviceInterface">The device interface of the child device that should change state</param>
        /// <param name="state">The custom state for the device.</param>
        /// <param name="message">A message providing more information about the state.</param>
        /// <remarks>
        /// This overload is used to change the state of a specific child device.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="state"/> is null.</exception>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="deviceInterface"/> is null.</exception>
        protected void OnCustomStateChanged(DeviceInterface deviceInterface, ICustomState state, string message)
        {
            if (state == null)
            {
                throw new ArgumentNullException("state");
            }

            if (deviceInterface == null)
            {
                throw new ArgumentNullException("deviceInterface");
            }

            OnCustomStateChanged(new CustomStateChangedEventArgs(Identifier, deviceInterface.Identifier, state, message));
        }


        protected virtual void Dispose(bool disposing)
        {
            if (!disposed)
            {
                if (disposing)
                {
                }

                disposed = true;
            }
        }
		
	

				
		 
		#region IGeoSpatialAwareWithAlt implementation
		
		public virtual Nullable<double> Altitude { get; set; }

		#endregion
  
		#region IGeoSpatialAware implementation
		
		public virtual int SpatialReferenceIdentifier { get; set; }
		
		public virtual double Longitude { get; set; }
		
		public virtual double Latitude { get; set; }

		#endregion
     }
	[GeneratedCode("Driver.Design", "1.0.0.0")]
	[Serializable]
    [ServiceBehaviorAttribute(InstanceContextMode = InstanceContextMode.Single)]
	public abstract class CameraBase : Device , IDisposable     {
		// -- constructors

		/// <summary>
        /// Initializes a new instance of the <see cref="CameraBase"/> class.
        /// </summary>
        protected CameraBase()
        {
        }

		// -- fields

		[NonSerialized]
		private bool disposed;

        // -- events	

		//Event declarations

		[field: NonSerialized]
        public event EventHandler<CustomStateChangedEventArgs> CustomStateChanged; 
        // -- properties	

		/// <summary>
        /// Unique identifier.
        /// </summary>
        public virtual string Id { get; set; }
		/// <summary>
        /// The parent device ID
        /// </summary>
        public virtual string ParentId { get; set; }
		/// <summary>
        /// Example Property for Device
        /// </summary>
        public virtual string DeviceName { get; set; }

		// -- public methods

		public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }
		
		


        // -- protected methods

		// Custom States

		/// <summary>
        /// Raises the <see cref="CustomStateChanged"/> event.
        /// </summary>
        /// <param name="e">The event arguments for the event.</param>
        /// <remarks>
        /// This should be raised after the device has come online if the device needs to report a connected but abnormal condition.
        /// These states can be defined on the driver design surface, and a number of common ones are available in the 
        /// CNL.IPSecurityCenter.Driver.CustomStates namespace
        /// </remarks>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="e"/> is null.</exception>
        protected virtual void OnCustomStateChanged(CustomStateChangedEventArgs e)
        {
            if (e == null)
            {
                throw new ArgumentNullException("e");
            }

            if (CustomStateChanged != null)
            {
                CustomStateChanged.Invoke(this, e);
            }
        }

        /// <summary>
        /// Raises the <see cref="CustomStateChanged"/> event.
        /// </summary>
        /// <param name="state">The custom state for the device.</param>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="state"/> is null.</exception>
        protected void OnCustomStateChanged(ICustomState state)
        {
            if (state == null)
            {
                throw new ArgumentNullException("state");
            }

            OnCustomStateChanged(new CustomStateChangedEventArgs(Identifier, state));
        }

        /// <summary>
        /// Raises the <see cref="CustomStateChanged"/> event.
        /// </summary>
        /// <param name="state">The custom state for the device.</param>
        /// <param name="message">A message providing more information about the state.</param>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="state"/> is null.</exception>
        protected void OnCustomStateChanged(ICustomState state, string message)
        {
            if (state == null)
            {
                throw new ArgumentNullException("state");
            }

            OnCustomStateChanged(new CustomStateChangedEventArgs(Identifier, state, message));
        }

        /// <summary>
        /// Raises the <see cref="CustomStateChanged"/> event.
        /// </summary>
        /// <param name="deviceInterface">The device interface of the child device that should change state</param>
        /// <param name="state">The custom state for the device.</param>
        /// <remarks>
        /// This overload is used to change the state of a specific child device.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="state"/> is null.</exception>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="deviceInterface"/> is null.</exception>
        protected void OnCustomStateChanged(DeviceInterface deviceInterface, ICustomState state)
        {
            if (state == null)
            {
                throw new ArgumentNullException("state");
            }

            if (deviceInterface == null)
            {
                throw new ArgumentNullException("deviceInterface");
            }

            OnCustomStateChanged(new CustomStateChangedEventArgs(Identifier, deviceInterface.Identifier, state));
        }

        /// <summary>
        /// Raises the <see cref="CustomStateChanged"/> event.
        /// </summary>
        /// <param name="deviceInterface">The device interface of the child device that should change state</param>
        /// <param name="state">The custom state for the device.</param>
        /// <param name="message">A message providing more information about the state.</param>
        /// <remarks>
        /// This overload is used to change the state of a specific child device.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="state"/> is null.</exception>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="deviceInterface"/> is null.</exception>
        protected void OnCustomStateChanged(DeviceInterface deviceInterface, ICustomState state, string message)
        {
            if (state == null)
            {
                throw new ArgumentNullException("state");
            }

            if (deviceInterface == null)
            {
                throw new ArgumentNullException("deviceInterface");
            }

            OnCustomStateChanged(new CustomStateChangedEventArgs(Identifier, deviceInterface.Identifier, state, message));
        }


        protected virtual void Dispose(bool disposing)
        {
            if (!disposed)
            {
                if (disposing)
                {
                }

                disposed = true;
            }
        }
		
	

				
		 
		#region IGeoSpatialAwareWithAlt implementation
		
		public virtual Nullable<double> Altitude { get; set; }

		#endregion
  
		#region IGeoSpatialAware implementation
		
		public virtual int SpatialReferenceIdentifier { get; set; }
		
		public virtual double Longitude { get; set; }
		
		public virtual double Latitude { get; set; }

		#endregion
     }
}