using System;
using System.Drawing;
using System.ServiceModel;
using System.Windows.Forms;
using System.Diagnostics.CodeAnalysis;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Threading.Tasks;
using CNL.IPSecurityCenter.Driver;
using CNL.IPSecurityCenter.Driver.Attributes;
using CNL.IPSecurityCenter.Driver.ServiceLocation;
using CNL.IPSecurityCenter.Driver.Video;
using CNL.IPSecurityCenter.Driver.Video.DeviceConnection;
using CNL.IPSecurityCenter.Driver.Video.Playback;
using CNL.IPSecurityCenter.Driver.Video.Export;
using CNL.IPSecurityCenter.Driver.Ptz;
using CNL.IPSecurityCenter.Driver.Attributes.Validation;
using VideoDeviceInterfaceDescriptor = CNL.IPSecurityCenter.Driver.Video.DeviceConnection.DeviceInterfaceDescriptor;
using CNL.IPSecurityCenter.Driver.Types.GeoSpatial;
 

//******************************************************************************
//*																			   *
//*																			   *
//*																			   *
//*  DO NOT MODIFY THIS FILE - IT IS AUTOGENERATED FROM THE CONNECTOR DIAGRAM  *
//*																			   *
//*																			   *
//*																			   *
//******************************************************************************

