
//******************************************************************************
//*																			   *
//*																			   *
//*																			   *
//*  DO NOT MODIFY THIS FILE - IT IS AUTOGENERATED FROM THE CONNECTOR DIAGRAM  *
//*																			   *
//*																			   *
//*																			   *
//******************************************************************************

using System;
using System.Drawing;
using System.ServiceModel;
using System.Windows.Forms;
using System.Diagnostics.CodeAnalysis;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Threading.Tasks;
using CNL.IPSecurityCenter.Driver;
using CNL.IPSecurityCenter.Driver.Attributes;
using CNL.IPSecurityCenter.Driver.ServiceLocation;
using CNL.IPSecurityCenter.Driver.Video;
using CNL.IPSecurityCenter.Driver.Video.DeviceConnection;
using CNL.IPSecurityCenter.Driver.Video.Playback;
using CNL.IPSecurityCenter.Driver.Video.Export;
using CNL.IPSecurityCenter.Driver.Ptz;
using CNL.IPSecurityCenter.Driver.Attributes.Validation;
using VideoDeviceInterfaceDescriptor = CNL.IPSecurityCenter.Driver.Video.DeviceConnection.DeviceInterfaceDescriptor;
using CNL.IPSecurityCenter.Driver.Types.GeoSpatial;


namespace Evbg.CC.Driver.SpotterGlobal.Radar
{ 

       
	[GeneratedCode("Driver.Design", "1.0.0.0"),
	SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces"),
    ServiceContract,
    Manufacturer(@"Spotter Global", @"Spotter Global, founded in 2009, develops Compact Surveillance Radar for military and commercial security. Based in Orem, Utah, it ensures high-quality, U.S.-made products with a global reach.", @"https://www.spotterglobal.com/", @"https://www.spotterglobal.com/contactus", @"Evbg.CC.Driver.SpotterGlobal.Radar.Images.spotter.jpeg", @"Spotter Global", typeof(IRadarServer)),
    Product(@"Radar Server", @"Radar Server", @"https://www.spotterglobal.com/", DeviceCategoryType.Other, @"Evbg.CC.Driver.SpotterGlobal.Radar.Images.spotter.jpeg", @"Radar", typeof(IRadarServer)),
    DisplayImage(DisplayImageSize.Image16x16, @"Evbg.CC.Driver.SpotterGlobal.Radar.Images.DeviceIcons.server16.jpg", typeof(IRadarServer)),
    DisplayImage(DisplayImageSize.Image24x24, @"Evbg.CC.Driver.SpotterGlobal.Radar.Images.DeviceIcons.server24.jpg", typeof(IRadarServer)),
    DisplayImage(DisplayImageSize.Image32x32, @"Evbg.CC.Driver.SpotterGlobal.Radar.Images.DeviceIcons.server32.jpg", typeof(IRadarServer)),
    DisplayImage(DisplayImageSize.Image64x64, @"Evbg.CC.Driver.SpotterGlobal.Radar.Images.DeviceIcons.server64.jpg", typeof(IRadarServer)),
	DeviceOverridesChildOnlineState]
    public partial interface IRadarServer : IDevice
		//Server device interfaces
		, INetworkedDevice
		//Client device interfaces
	    
	{
		// -- events
		
        /// <summary>
        /// Generic Server Event
        /// </summary>
        [DeviceEvent,
        DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameRadarServerServerEvent", typeof(IRadarServer)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionRadarServerServerEvent", typeof(IRadarServer))]
        event EventHandler<ServerEventEventArgs> ServerEventEvent;

		// -- properties

		
		/// <summary>
        /// Time interval in seconds between web service connectivity checks.
        /// </summary>
        [CategoryAdvancedAttribute]
		[DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameRadarServerKeepAliveInterval", typeof(IRadarServer)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionRadarServerKeepAliveInterval", typeof(IRadarServer))]
		[CNL.IPSecurityCenter.Driver.Attributes.Validation.IntegerConstraint(MinValue=0, MaxValue=int.MaxValue)]
		[System.ComponentModel.DefaultValue(10)]
        int KeepAliveInterval 
		{  
			[OperationContract]  get; 
			[OperationContract]  set; 
		}
		
		/// <summary>
        /// Maximum devices allowed to populate at a time.
        /// </summary>
        [CategoryAdvancedAttribute]
		[DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameRadarServerDevicePopulationBatchSize", typeof(IRadarServer)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionRadarServerDevicePopulationBatchSize", typeof(IRadarServer))]
		[CNL.IPSecurityCenter.Driver.Attributes.Validation.IntegerConstraint(MinValue=20, MaxValue=100)]
		[System.ComponentModel.DefaultValue(50)]
        int DevicePopulationBatchSize 
		{  
			[OperationContract]  get; 
			[OperationContract]  set; 
		}
		
		/// <summary>
        /// Logging level of the driver.
        /// </summary>
        [CategoryAdvancedAttribute]
		[DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameRadarServerLogLevel", typeof(IRadarServer)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionRadarServerLogLevel", typeof(IRadarServer))]
        CNL.IPSecurityCenter.Driver.Utility.Logging.LogLevel LogLevel 
		{  
			[OperationContract]  get; 
			[OperationContract]  set; 
		}
		
		/// <summary>
        /// Example Property for Server
        /// </summary>
        [CategoryPropertiesAttribute]
		[DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameRadarServerListnerPort", typeof(IRadarServer)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionRadarServerListnerPort", typeof(IRadarServer))]
		[DeviceWizard]
		[System.ComponentModel.DefaultValue(6588)]
        int ListnerPort 
		{  
			[OperationContract]  get; 
			[OperationContract]  set; 
		}
		
		/// <summary>
        /// When true, the connector simulates the subsystem instead of connecting to a real one.
        /// </summary>
        [CategoryAdvancedAttribute]
		[DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameRadarServerSimulationMode", typeof(IRadarServer)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionRadarServerSimulationMode", typeof(IRadarServer))]
		[DeviceWizard]
        bool SimulationMode 
		{  
			[OperationContract]  get; 
			[OperationContract]  set; 
		}
		
		/// <summary>
        /// Time interval in miliseconds between web service connectivity checks.
        /// </summary>
        [CategoryAdvancedAttribute]
		[DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameRadarServerPollingInterval", typeof(IRadarServer)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionRadarServerPollingInterval", typeof(IRadarServer))]
		[CNL.IPSecurityCenter.Driver.Attributes.Validation.IntegerConstraint(MinValue=0, MaxValue=int.MaxValue)]
		[System.ComponentModel.DefaultValue(1000)]
        int PollingInterval 
		{  
			[OperationContract]  get; 
			[OperationContract]  set; 
		}
		
		// -- methods


        /// <summary>
        /// Refresh the devices to match the current configuration on Generic server.
        /// </summary>
        [CategoryActionsAttribute]
		[DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameRadarServerRefreshDevices", typeof(IRadarServer)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionRadarServerRefreshDevices", typeof(IRadarServer))]		
		[OperationContract]				
		bool RefreshDevices(			
			[CategoryParametersAttribute]
            [DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameRadarServerRefreshDevicesrefreshProperties", typeof(IRadarServer)),
            Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionRadarServerRefreshDevicesrefreshProperties", typeof(IRadarServer))]
			bool refreshProperties);


        /// <summary>
        /// Sample Server Method
        /// </summary>
        [CategoryActionsAttribute]
		[DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameRadarServerSampleServerMethod", typeof(IRadarServer)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionRadarServerSampleServerMethod", typeof(IRadarServer))]		
		[OperationContract]				
		void SampleServerMethod();

	}
       
	[GeneratedCode("Driver.Design", "1.0.0.0"),
	SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces"),
    ServiceContract,
    Manufacturer(@"Spotter Global", @"Spotter Global, founded in 2009, develops Compact Surveillance Radar for military and commercial security. Based in Orem, Utah, it ensures high-quality, U.S.-made products with a global reach.", @"https://www.spotterglobal.com/", @"https://www.spotterglobal.com/contactus", @"Evbg.CC.Driver.SpotterGlobal.Radar.Images.spotter.jpeg", @"Spotter Global", typeof(IRadar)),
    Product(@"Radar Device", @"Radar", @"", DeviceCategoryType.Other, @"Evbg.CC.Driver.SpotterGlobal.Radar.", @"Radar", typeof(IRadar)),
    DisplayImage(DisplayImageSize.Image16x16, @"Evbg.CC.Driver.SpotterGlobal.Radar.Images.DeviceIcons.radar16.png", typeof(IRadar)),
    DisplayImage(DisplayImageSize.Image24x24, @"Evbg.CC.Driver.SpotterGlobal.Radar.Images.DeviceIcons.radar24.png", typeof(IRadar)),
    DisplayImage(DisplayImageSize.Image32x32, @"Evbg.CC.Driver.SpotterGlobal.Radar.Images.DeviceIcons.radar32.png", typeof(IRadar)),
    DisplayImage(DisplayImageSize.Image64x64, @"Evbg.CC.Driver.SpotterGlobal.Radar.Images.DeviceIcons.radar64.png", typeof(IRadar)),
	DeviceOverridesChildOnlineState]
    public partial interface IRadar : IDevice
		//Server device interfaces
		, IRaiseCustomStates
		//Client device interfaces
	 , IGeoSpatialAware  , IGeoSpatialAwareWithAlt     
	{
		// -- events
		
        /// <summary>
        /// Generic Device Event
        /// </summary>
        [DeviceEvent,
        DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameRadarDeviceEvent", typeof(IRadar)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionRadarDeviceEvent", typeof(IRadar))]
        event EventHandler<DeviceEventEventArgs> DeviceEventEvent;

        /// <summary>
        /// Alarm Track Recieved
        /// </summary>
        [DeviceEvent,
        DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameRadarAlarmTrackRecieved", typeof(IRadar)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionRadarAlarmTrackRecieved", typeof(IRadar))]
        event EventHandler<AlarmTrackRecievedEventArgs> AlarmTrackRecievedEvent;

		// -- properties

		
		/// <summary>
        /// Unique identifier.
        /// </summary>
        [CategoryPropertiesAttribute]
		[DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameRadarId", typeof(IRadar)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionRadarId", typeof(IRadar))]
		[CNL.IPSecurityCenter.Driver.Attributes.Validation.StringConstraint("The ID must not be empty",AllowNull = false,AllowEmpty = false)]
		[DeviceWizard]
		[System.ComponentModel.ReadOnly(true)]
        string Id 
		{  
			[OperationContract]  get; 
			[OperationContract]  set; 
		}
		
		/// <summary>
        /// The parent device ID
        /// </summary>
        [CategoryPropertiesAttribute]
		[DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameRadarParentId", typeof(IRadar)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionRadarParentId", typeof(IRadar))]
		[CNL.IPSecurityCenter.Driver.Attributes.Validation.StringConstraint("The API key must not be empty",AllowNull = false)]
		[DeviceWizard]
		[System.ComponentModel.ReadOnly(true)]
        string ParentId 
		{  
			[OperationContract]  get; 
			[OperationContract]  set; 
		}
		
		/// <summary>
        /// Device Name
        /// </summary>
        [CategoryPropertiesAttribute]
		[DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameRadarDeviceName", typeof(IRadar)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionRadarDeviceName", typeof(IRadar))]
		[DeviceWizard]
		[System.ComponentModel.DefaultValue("")]
        string DeviceName 
		{  
			[OperationContract]  get; 
			[OperationContract]  set; 
		}
		
		// -- methods


        /// <summary>
        /// Get Device Details
        /// </summary>
        [CategoryActionsAttribute]
		[DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameRadarGetDeviceDetails", typeof(IRadar)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionRadarGetDeviceDetails", typeof(IRadar))]		
		[OperationContract]				
		void GetDeviceDetails(			
			[CategoryParametersAttribute]
            [DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameRadarGetDeviceDetailsDeviceId", typeof(IRadar)),
            Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionRadarGetDeviceDetailsDeviceId", typeof(IRadar))]
			string DeviceId);

	}
       
	[GeneratedCode("Driver.Design", "1.0.0.0"),
	SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces"),
    ServiceContract,
    Manufacturer(@"Spotter Global", @"Spotter Global, founded in 2009, develops Compact Surveillance Radar for military and commercial security. Based in Orem, Utah, it ensures high-quality, U.S.-made products with a global reach.", @"https://www.spotterglobal.com/", @"https://www.spotterglobal.com/contactus", @"Evbg.CC.Driver.SpotterGlobal.Radar.Images.spotter.jpeg", @"Spotter Global", typeof(IZone)),
    Product(@"Zone Device", @"Zone", @"", DeviceCategoryType.Other, @"Evbg.CC.Driver.SpotterGlobal.Radar.", @"Zone", typeof(IZone)),
    DisplayImage(DisplayImageSize.Image16x16, @"Evbg.CC.Driver.SpotterGlobal.Radar.Images.DeviceIcons.zone16.png", typeof(IZone)),
    DisplayImage(DisplayImageSize.Image24x24, @"Evbg.CC.Driver.SpotterGlobal.Radar.Images.DeviceIcons.zone24.png", typeof(IZone)),
    DisplayImage(DisplayImageSize.Image32x32, @"Evbg.CC.Driver.SpotterGlobal.Radar.Images.DeviceIcons.zone32.png", typeof(IZone)),
    DisplayImage(DisplayImageSize.Image64x64, @"Evbg.CC.Driver.SpotterGlobal.Radar.Images.DeviceIcons.zone64.png", typeof(IZone)),
	DeviceOverridesChildOnlineState]
    public partial interface IZone : IDevice
		//Server device interfaces
		, IRaiseCustomStates
		//Client device interfaces
	 , IGeoSpatialAwareWithAlt  , IGeoSpatialAware     
	{
		// -- events
		
        /// <summary>
        /// Track Update
        /// </summary>
        [DeviceEvent,
        DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameZoneTrackUpdate", typeof(IZone)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionZoneTrackUpdate", typeof(IZone))]
        event EventHandler<TrackUpdateEventArgs> TrackUpdateEvent;

		// -- properties

		
		/// <summary>
        /// Unique identifier.
        /// </summary>
        [CategoryPropertiesAttribute]
		[DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameZoneId", typeof(IZone)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionZoneId", typeof(IZone))]
		[CNL.IPSecurityCenter.Driver.Attributes.Validation.StringConstraint("The ID must not be empty",AllowNull = false,AllowEmpty = false)]
		[DeviceWizard]
		[System.ComponentModel.ReadOnly(true)]
        string Id 
		{  
			[OperationContract]  get; 
			[OperationContract]  set; 
		}
		
		/// <summary>
        /// The parent device ID
        /// </summary>
        [CategoryPropertiesAttribute]
		[DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameZoneParentId", typeof(IZone)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionZoneParentId", typeof(IZone))]
		[CNL.IPSecurityCenter.Driver.Attributes.Validation.StringConstraint("The API key must not be empty",AllowNull = false)]
		[DeviceWizard]
		[System.ComponentModel.ReadOnly(true)]
        string ParentId 
		{  
			[OperationContract]  get; 
			[OperationContract]  set; 
		}
		
		/// <summary>
        /// Type String
        /// </summary>
        [CategoryPropertiesAttribute]
		[DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameZoneTypeString", typeof(IZone)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionZoneTypeString", typeof(IZone))]
		[DeviceWizard]
		[System.ComponentModel.DefaultValue("")]
        string TypeString 
		{  
			[OperationContract]  get; 
			[OperationContract]  set; 
		}
		
		/// <summary>
        /// Active
        /// </summary>
        [CategoryPropertiesAttribute]
		[DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameZoneActive", typeof(IZone)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionZoneActive", typeof(IZone))]
		[DeviceWizard]
        string Active 
		{  
			[OperationContract]  get; 
			[OperationContract]  set; 
		}
		
		/// <summary>
        /// Device Name
        /// </summary>
        [CategoryPropertiesAttribute]
		[DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameZoneDeviceName", typeof(IZone)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionZoneDeviceName", typeof(IZone))]
		[DeviceWizard]
        string DeviceName 
		{  
			[OperationContract]  get; 
			[OperationContract]  set; 
		}
		
		// -- methods

	}
       
	[GeneratedCode("Driver.Design", "1.0.0.0"),
	SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces"),
    ServiceContract,
    Manufacturer(@"Spotter Global", @"Spotter Global, founded in 2009, develops Compact Surveillance Radar for military and commercial security. Based in Orem, Utah, it ensures high-quality, U.S.-made products with a global reach.", @"https://www.spotterglobal.com/", @"https://www.spotterglobal.com/contactus", @"Evbg.CC.Driver.SpotterGlobal.Radar.Images.spotter.jpeg", @"Spotter Global", typeof(IUDC)),
    Product(@"UDC Device", @"UDC", @"", DeviceCategoryType.Other, @"Evbg.CC.Driver.SpotterGlobal.Radar.", @"UDC", typeof(IUDC)),
    DisplayImage(DisplayImageSize.Image16x16, @"Evbg.CC.Driver.SpotterGlobal.Radar.Images.DeviceIcons.udc16.jpeg", typeof(IUDC)),
    DisplayImage(DisplayImageSize.Image24x24, @"Evbg.CC.Driver.SpotterGlobal.Radar.Images.DeviceIcons.udc24.jpeg", typeof(IUDC)),
    DisplayImage(DisplayImageSize.Image32x32, @"Evbg.CC.Driver.SpotterGlobal.Radar.Images.DeviceIcons.udc32.jpeg", typeof(IUDC)),
    DisplayImage(DisplayImageSize.Image64x64, @"Evbg.CC.Driver.SpotterGlobal.Radar.Images.DeviceIcons.udc64.jpeg", typeof(IUDC)),
	DeviceOverridesChildOnlineState]
    public partial interface IUDC : IDevice
		//Server device interfaces
		, IRaiseCustomStates
		//Client device interfaces
	 , IGeoSpatialAwareWithAlt  , IGeoSpatialAware     
	{
		// -- events
		
		// -- properties

		
		/// <summary>
        /// Unique identifier.
        /// </summary>
        [CategoryPropertiesAttribute]
		[DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameUDCId", typeof(IUDC)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionUDCId", typeof(IUDC))]
		[CNL.IPSecurityCenter.Driver.Attributes.Validation.StringConstraint("The ID must not be empty",AllowNull = false,AllowEmpty = false)]
		[DeviceWizard]
		[System.ComponentModel.ReadOnly(true)]
        string Id 
		{  
			[OperationContract]  get; 
			[OperationContract]  set; 
		}
		
		/// <summary>
        /// The parent device ID
        /// </summary>
        [CategoryPropertiesAttribute]
		[DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameUDCParentId", typeof(IUDC)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionUDCParentId", typeof(IUDC))]
		[CNL.IPSecurityCenter.Driver.Attributes.Validation.StringConstraint("The API key must not be empty",AllowNull = false)]
		[DeviceWizard]
		[System.ComponentModel.ReadOnly(true)]
        string ParentId 
		{  
			[OperationContract]  get; 
			[OperationContract]  set; 
		}
		
		/// <summary>
        /// Device Name
        /// </summary>
        [CategoryPropertiesAttribute]
		[DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameUDCDeviceName", typeof(IUDC)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionUDCDeviceName", typeof(IUDC))]
		[DeviceWizard]
		[System.ComponentModel.DefaultValue("")]
        string DeviceName 
		{  
			[OperationContract]  get; 
			[OperationContract]  set; 
		}
		
		// -- methods

	}
       
	[GeneratedCode("Driver.Design", "1.0.0.0"),
	SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces"),
    ServiceContract,
    Manufacturer(@"Spotter Global", @"Spotter Global, founded in 2009, develops Compact Surveillance Radar for military and commercial security. Based in Orem, Utah, it ensures high-quality, U.S.-made products with a global reach.", @"https://www.spotterglobal.com/", @"https://www.spotterglobal.com/contactus", @"Evbg.CC.Driver.SpotterGlobal.Radar.Images.spotter.jpeg", @"Spotter Global", typeof(ICamera)),
    Product(@"Camera Device", @"Camera", @"", DeviceCategoryType.Other, @"Evbg.CC.Driver.SpotterGlobal.Radar.", @"Camera", typeof(ICamera)),
    DisplayImage(DisplayImageSize.Image16x16, @"Evbg.CC.Driver.SpotterGlobal.Radar.Images.DeviceIcons.camera16.png", typeof(ICamera)),
    DisplayImage(DisplayImageSize.Image24x24, @"Evbg.CC.Driver.SpotterGlobal.Radar.Images.DeviceIcons.camera24.png", typeof(ICamera)),
    DisplayImage(DisplayImageSize.Image32x32, @"Evbg.CC.Driver.SpotterGlobal.Radar.Images.DeviceIcons.camera32.png", typeof(ICamera)),
    DisplayImage(DisplayImageSize.Image64x64, @"Evbg.CC.Driver.SpotterGlobal.Radar.Images.DeviceIcons.camera64.png", typeof(ICamera)),
	DeviceOverridesChildOnlineState]
    public partial interface ICamera : IDevice
		//Server device interfaces
		, IRaiseCustomStates
		//Client device interfaces
	 , IGeoSpatialAwareWithAlt  , IGeoSpatialAware     
	{
		// -- events
		
		// -- properties

		
		/// <summary>
        /// Unique identifier.
        /// </summary>
        [CategoryPropertiesAttribute]
		[DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameCameraId", typeof(ICamera)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionCameraId", typeof(ICamera))]
		[CNL.IPSecurityCenter.Driver.Attributes.Validation.StringConstraint("The ID must not be empty",AllowNull = false,AllowEmpty = false)]
		[DeviceWizard]
		[System.ComponentModel.ReadOnly(true)]
        string Id 
		{  
			[OperationContract]  get; 
			[OperationContract]  set; 
		}
		
		/// <summary>
        /// The parent device ID
        /// </summary>
        [CategoryPropertiesAttribute]
		[DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameCameraParentId", typeof(ICamera)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionCameraParentId", typeof(ICamera))]
		[CNL.IPSecurityCenter.Driver.Attributes.Validation.StringConstraint("The API key must not be empty",AllowNull = false)]
		[DeviceWizard]
		[System.ComponentModel.ReadOnly(true)]
        string ParentId 
		{  
			[OperationContract]  get; 
			[OperationContract]  set; 
		}
		
		/// <summary>
        /// Example Property for Device
        /// </summary>
        [CategoryPropertiesAttribute]
		[DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameCameraDeviceName", typeof(ICamera)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionCameraDeviceName", typeof(ICamera))]
		[DeviceWizard]
		[System.ComponentModel.DefaultValue("")]
        string DeviceName 
		{  
			[OperationContract]  get; 
			[OperationContract]  set; 
		}
		
		// -- methods

	}
}