//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evbg.CC.Driver.SpotterGlobal.Radar {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Design_driverdesign_Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Design_driverdesign_Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", typeof(Design_driverdesign_Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearing.
        /// </summary>
        internal static string DescriptionAlarmTrackRecievedBearing {
            get {
                return ResourceManager.GetString("DescriptionAlarmTrackRecievedBearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidence.
        /// </summary>
        internal static string DescriptionAlarmTrackRecievedConfidence {
            get {
                return ResourceManager.GetString("DescriptionAlarmTrackRecievedConfidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intial Alarm Date Time.
        /// </summary>
        internal static string DescriptionAlarmTrackRecievedIntialAlarmDateTime {
            get {
                return ResourceManager.GetString("DescriptionAlarmTrackRecievedIntialAlarmDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string DescriptionAlarmTrackRecievedLongitude {
            get {
                return ResourceManager.GetString("DescriptionAlarmTrackRecievedLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Category.
        /// </summary>
        internal static string DescriptionAlarmTrackRecievedObjectCategory {
            get {
                return ResourceManager.GetString("DescriptionAlarmTrackRecievedObjectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Id.
        /// </summary>
        internal static string DescriptionAlarmTrackRecievedTrackId {
            get {
                return ResourceManager.GetString("DescriptionAlarmTrackRecievedTrackId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity.
        /// </summary>
        internal static string DescriptionAlarmTrackRecievedVelocity {
            get {
                return ResourceManager.GetString("DescriptionAlarmTrackRecievedVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example Property for Device.
        /// </summary>
        internal static string DescriptionCameraDeviceName {
            get {
                return ResourceManager.GetString("DescriptionCameraDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique identifier..
        /// </summary>
        internal static string DescriptionCameraId {
            get {
                return ResourceManager.GetString("DescriptionCameraId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent device ID.
        /// </summary>
        internal static string DescriptionCameraParentId {
            get {
                return ResourceManager.GetString("DescriptionCameraParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Property.
        /// </summary>
        internal static string DescriptionDeviceEventSampleProperty {
            get {
                return ResourceManager.GetString("DescriptionDeviceEventSampleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geospatial Aware Event.
        /// </summary>
        internal static string DescriptionGeospatialAwareEvent {
            get {
                return ResourceManager.GetString("DescriptionGeospatialAwareEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event description..
        /// </summary>
        internal static string DescriptionGeospatialAwareEventDescription {
            get {
                return ResourceManager.GetString("DescriptionGeospatialAwareEventDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Track Recieved.
        /// </summary>
        internal static string DescriptionRadarAlarmTrackRecieved {
            get {
                return ResourceManager.GetString("DescriptionRadarAlarmTrackRecieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic Device Event.
        /// </summary>
        internal static string DescriptionRadarDeviceEvent {
            get {
                return ResourceManager.GetString("DescriptionRadarDeviceEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Name.
        /// </summary>
        internal static string DescriptionRadarDeviceName {
            get {
                return ResourceManager.GetString("DescriptionRadarDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Device Details.
        /// </summary>
        internal static string DescriptionRadarGetDeviceDetails {
            get {
                return ResourceManager.GetString("DescriptionRadarGetDeviceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Id.
        /// </summary>
        internal static string DescriptionRadarGetDeviceDetailsDeviceId {
            get {
                return ResourceManager.GetString("DescriptionRadarGetDeviceDetailsDeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique identifier..
        /// </summary>
        internal static string DescriptionRadarId {
            get {
                return ResourceManager.GetString("DescriptionRadarId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent device ID.
        /// </summary>
        internal static string DescriptionRadarParentId {
            get {
                return ResourceManager.GetString("DescriptionRadarParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum devices allowed to populate at a time..
        /// </summary>
        internal static string DescriptionRadarServerDevicePopulationBatchSize {
            get {
                return ResourceManager.GetString("DescriptionRadarServerDevicePopulationBatchSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time interval in seconds between web service connectivity checks..
        /// </summary>
        internal static string DescriptionRadarServerKeepAliveInterval {
            get {
                return ResourceManager.GetString("DescriptionRadarServerKeepAliveInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example Property for Server.
        /// </summary>
        internal static string DescriptionRadarServerListnerPort {
            get {
                return ResourceManager.GetString("DescriptionRadarServerListnerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging level of the driver..
        /// </summary>
        internal static string DescriptionRadarServerLogLevel {
            get {
                return ResourceManager.GetString("DescriptionRadarServerLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time interval in miliseconds between web service connectivity checks..
        /// </summary>
        internal static string DescriptionRadarServerPollingInterval {
            get {
                return ResourceManager.GetString("DescriptionRadarServerPollingInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh the devices to match the current configuration on Generic server..
        /// </summary>
        internal static string DescriptionRadarServerRefreshDevices {
            get {
                return ResourceManager.GetString("DescriptionRadarServerRefreshDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronise device properties and labels..
        /// </summary>
        internal static string DescriptionRadarServerRefreshDevicesrefreshProperties {
            get {
                return ResourceManager.GetString("DescriptionRadarServerRefreshDevicesrefreshProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Server Method.
        /// </summary>
        internal static string DescriptionRadarServerSampleServerMethod {
            get {
                return ResourceManager.GetString("DescriptionRadarServerSampleServerMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic Server Event.
        /// </summary>
        internal static string DescriptionRadarServerServerEvent {
            get {
                return ResourceManager.GetString("DescriptionRadarServerServerEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When true, the connector simulates the subsystem instead of connecting to a real one..
        /// </summary>
        internal static string DescriptionRadarServerSimulationMode {
            get {
                return ResourceManager.GetString("DescriptionRadarServerSimulationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Property.
        /// </summary>
        internal static string DescriptionServerEventSampleProperty {
            get {
                return ResourceManager.GetString("DescriptionServerEventSampleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        internal static string DescriptionTrackUpdateAltitude {
            get {
                return ResourceManager.GetString("DescriptionTrackUpdateAltitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearing.
        /// </summary>
        internal static string DescriptionTrackUpdateBearing {
            get {
                return ResourceManager.GetString("DescriptionTrackUpdateBearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity.
        /// </summary>
        internal static string DescriptionTrackUpdateVelocity {
            get {
                return ResourceManager.GetString("DescriptionTrackUpdateVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Name.
        /// </summary>
        internal static string DescriptionUDCDeviceName {
            get {
                return ResourceManager.GetString("DescriptionUDCDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique identifier..
        /// </summary>
        internal static string DescriptionUDCId {
            get {
                return ResourceManager.GetString("DescriptionUDCId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent device ID.
        /// </summary>
        internal static string DescriptionUDCParentId {
            get {
                return ResourceManager.GetString("DescriptionUDCParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string DescriptionZoneActive {
            get {
                return ResourceManager.GetString("DescriptionZoneActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Name.
        /// </summary>
        internal static string DescriptionZoneDeviceName {
            get {
                return ResourceManager.GetString("DescriptionZoneDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique identifier..
        /// </summary>
        internal static string DescriptionZoneId {
            get {
                return ResourceManager.GetString("DescriptionZoneId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent device ID.
        /// </summary>
        internal static string DescriptionZoneParentId {
            get {
                return ResourceManager.GetString("DescriptionZoneParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Update.
        /// </summary>
        internal static string DescriptionZoneTrackUpdate {
            get {
                return ResourceManager.GetString("DescriptionZoneTrackUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type String.
        /// </summary>
        internal static string DescriptionZoneTypeString {
            get {
                return ResourceManager.GetString("DescriptionZoneTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearing.
        /// </summary>
        internal static string DisplayNameAlarmTrackRecievedBearing {
            get {
                return ResourceManager.GetString("DisplayNameAlarmTrackRecievedBearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidence.
        /// </summary>
        internal static string DisplayNameAlarmTrackRecievedConfidence {
            get {
                return ResourceManager.GetString("DisplayNameAlarmTrackRecievedConfidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intial Alarm Date Time.
        /// </summary>
        internal static string DisplayNameAlarmTrackRecievedIntialAlarmDateTime {
            get {
                return ResourceManager.GetString("DisplayNameAlarmTrackRecievedIntialAlarmDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string DisplayNameAlarmTrackRecievedLongitude {
            get {
                return ResourceManager.GetString("DisplayNameAlarmTrackRecievedLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Category.
        /// </summary>
        internal static string DisplayNameAlarmTrackRecievedObjectCategory {
            get {
                return ResourceManager.GetString("DisplayNameAlarmTrackRecievedObjectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Id.
        /// </summary>
        internal static string DisplayNameAlarmTrackRecievedTrackId {
            get {
                return ResourceManager.GetString("DisplayNameAlarmTrackRecievedTrackId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity.
        /// </summary>
        internal static string DisplayNameAlarmTrackRecievedVelocity {
            get {
                return ResourceManager.GetString("DisplayNameAlarmTrackRecievedVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceName.
        /// </summary>
        internal static string DisplayNameCameraDeviceName {
            get {
                return ResourceManager.GetString("DisplayNameCameraDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string DisplayNameCameraId {
            get {
                return ResourceManager.GetString("DisplayNameCameraId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent ID.
        /// </summary>
        internal static string DisplayNameCameraParentId {
            get {
                return ResourceManager.GetString("DisplayNameCameraParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Property.
        /// </summary>
        internal static string DisplayNameDeviceEventSampleProperty {
            get {
                return ResourceManager.GetString("DisplayNameDeviceEventSampleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geospatial Aware Event.
        /// </summary>
        internal static string DisplayNameGeospatialAwareEvent {
            get {
                return ResourceManager.GetString("DisplayNameGeospatialAwareEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DisplayNameGeospatialAwareEventDescription {
            get {
                return ResourceManager.GetString("DisplayNameGeospatialAwareEventDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Track Recieved.
        /// </summary>
        internal static string DisplayNameRadarAlarmTrackRecieved {
            get {
                return ResourceManager.GetString("DisplayNameRadarAlarmTrackRecieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Event.
        /// </summary>
        internal static string DisplayNameRadarDeviceEvent {
            get {
                return ResourceManager.GetString("DisplayNameRadarDeviceEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceName.
        /// </summary>
        internal static string DisplayNameRadarDeviceName {
            get {
                return ResourceManager.GetString("DisplayNameRadarDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Device Details.
        /// </summary>
        internal static string DisplayNameRadarGetDeviceDetails {
            get {
                return ResourceManager.GetString("DisplayNameRadarGetDeviceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Id.
        /// </summary>
        internal static string DisplayNameRadarGetDeviceDetailsDeviceId {
            get {
                return ResourceManager.GetString("DisplayNameRadarGetDeviceDetailsDeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string DisplayNameRadarId {
            get {
                return ResourceManager.GetString("DisplayNameRadarId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent ID.
        /// </summary>
        internal static string DisplayNameRadarParentId {
            get {
                return ResourceManager.GetString("DisplayNameRadarParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Population Batch Size.
        /// </summary>
        internal static string DisplayNameRadarServerDevicePopulationBatchSize {
            get {
                return ResourceManager.GetString("DisplayNameRadarServerDevicePopulationBatchSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Alive Interval.
        /// </summary>
        internal static string DisplayNameRadarServerKeepAliveInterval {
            get {
                return ResourceManager.GetString("DisplayNameRadarServerKeepAliveInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListnerPort.
        /// </summary>
        internal static string DisplayNameRadarServerListnerPort {
            get {
                return ResourceManager.GetString("DisplayNameRadarServerListnerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Level.
        /// </summary>
        internal static string DisplayNameRadarServerLogLevel {
            get {
                return ResourceManager.GetString("DisplayNameRadarServerLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polling Interval.
        /// </summary>
        internal static string DisplayNameRadarServerPollingInterval {
            get {
                return ResourceManager.GetString("DisplayNameRadarServerPollingInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Devices.
        /// </summary>
        internal static string DisplayNameRadarServerRefreshDevices {
            get {
                return ResourceManager.GetString("DisplayNameRadarServerRefreshDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Properties.
        /// </summary>
        internal static string DisplayNameRadarServerRefreshDevicesrefreshProperties {
            get {
                return ResourceManager.GetString("DisplayNameRadarServerRefreshDevicesrefreshProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Server Method.
        /// </summary>
        internal static string DisplayNameRadarServerSampleServerMethod {
            get {
                return ResourceManager.GetString("DisplayNameRadarServerSampleServerMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Event.
        /// </summary>
        internal static string DisplayNameRadarServerServerEvent {
            get {
                return ResourceManager.GetString("DisplayNameRadarServerServerEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation Mode.
        /// </summary>
        internal static string DisplayNameRadarServerSimulationMode {
            get {
                return ResourceManager.GetString("DisplayNameRadarServerSimulationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Property.
        /// </summary>
        internal static string DisplayNameServerEventSampleProperty {
            get {
                return ResourceManager.GetString("DisplayNameServerEventSampleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        internal static string DisplayNameTrackUpdateAltitude {
            get {
                return ResourceManager.GetString("DisplayNameTrackUpdateAltitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearing.
        /// </summary>
        internal static string DisplayNameTrackUpdateBearing {
            get {
                return ResourceManager.GetString("DisplayNameTrackUpdateBearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity.
        /// </summary>
        internal static string DisplayNameTrackUpdateVelocity {
            get {
                return ResourceManager.GetString("DisplayNameTrackUpdateVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceName.
        /// </summary>
        internal static string DisplayNameUDCDeviceName {
            get {
                return ResourceManager.GetString("DisplayNameUDCDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string DisplayNameUDCId {
            get {
                return ResourceManager.GetString("DisplayNameUDCId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent ID.
        /// </summary>
        internal static string DisplayNameUDCParentId {
            get {
                return ResourceManager.GetString("DisplayNameUDCParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string DisplayNameZoneActive {
            get {
                return ResourceManager.GetString("DisplayNameZoneActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceName.
        /// </summary>
        internal static string DisplayNameZoneDeviceName {
            get {
                return ResourceManager.GetString("DisplayNameZoneDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string DisplayNameZoneId {
            get {
                return ResourceManager.GetString("DisplayNameZoneId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent ID.
        /// </summary>
        internal static string DisplayNameZoneParentId {
            get {
                return ResourceManager.GetString("DisplayNameZoneParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Update.
        /// </summary>
        internal static string DisplayNameZoneTrackUpdate {
            get {
                return ResourceManager.GetString("DisplayNameZoneTrackUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeString.
        /// </summary>
        internal static string DisplayNameZoneTypeString {
            get {
                return ResourceManager.GetString("DisplayNameZoneTypeString", resourceCulture);
            }
        }
    }
}
