using System;
using System.Drawing;
using System.ServiceModel;
using System.Windows.Forms;
using System.Diagnostics.CodeAnalysis;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Threading.Tasks;
using CNL.IPSecurityCenter.Driver;
using CNL.IPSecurityCenter.Driver.Attributes;
using CNL.IPSecurityCenter.Driver.ServiceLocation;
using CNL.IPSecurityCenter.Driver.Video;
using CNL.IPSecurityCenter.Driver.Video.DeviceConnection;
using CNL.IPSecurityCenter.Driver.Video.Playback;
using CNL.IPSecurityCenter.Driver.Video.Export;
using CNL.IPSecurityCenter.Driver.Ptz;
using CNL.IPSecurityCenter.Driver.Attributes.Validation;
using VideoDeviceInterfaceDescriptor = CNL.IPSecurityCenter.Driver.Video.DeviceConnection.DeviceInterfaceDescriptor;
using CNL.IPSecurityCenter.Driver.Types.GeoSpatial;


//******************************************************************************
//*																			   *
//*																			   *
//*																			   *
//*  DO NOT MODIFY THIS FILE - IT IS AUTOGENERATED FROM THE CONNECTOR DIAGRAM  *
//*																			   *
//*																			   *
//*																			   *
//******************************************************************************

namespace Evbg.CC.Driver.SpotterGlobal.Radar
{
    /// <summary>
    /// Geospatial Aware Event
    /// </summary>
    [GeneratedCode("Driver.Design", "1.0.0.0")]
    [Serializable]
    public partial class GeospatialAwareEventEventArgs : DeviceEventArgs
	, IGeoSpatialAwareWithAltEvent	, IGeoSpatialAwareEvent    {
        internal GeospatialAwareEventEventArgs(IDevice device)
            :  base(device.Identifier)         {           
        }

		internal GeospatialAwareEventEventArgs(IDevice device, DateTime date)
             :  base(device.Identifier, date)         {           
        }

        // -- properties
		
		/// <summary>
        /// Event description.
        /// </summary>
		[CategoryPropertiesAttribute]
        [DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameGeospatialAwareEventDescription", typeof(GeospatialAwareEventEventArgs)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionGeospatialAwareEventDescription", typeof(GeospatialAwareEventEventArgs))]
        public string Description { get; set; }
		
		
		#region IGeoSpatialAwareWithAltEvent implementation
		
		public virtual Nullable<double> Altitude { get; set; }
		
		public virtual Nullable<double> VerticalRate { get; set; }
		
#endregion

		#region IGeoSpatialAwareEvent implementation
		
		public virtual int SpatialReferenceIdentifier { get; set; }
		
		public virtual Nullable<double> Longitude { get; set; }
		
		public virtual Nullable<double> Latitude { get; set; }
		
		public virtual Nullable<double> Heading { get; set; }
		
		public virtual Nullable<double> Speed { get; set; }
		
#endregion
	}
    /// <summary>
    /// Generic Device Event
    /// </summary>
    [GeneratedCode("Driver.Design", "1.0.0.0")]
    [Serializable]
    public partial class DeviceEventEventArgs : GeospatialAwareEventEventArgs
    {
        internal DeviceEventEventArgs(IDevice device)
            :  base(device)         {           
        }

		internal DeviceEventEventArgs(IDevice device, DateTime date)
             :  base(device, date)         {           
        }

        // -- properties
		
		/// <summary>
        /// Sample Property
        /// </summary>
		[CategoryPropertiesAttribute]
        [DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameDeviceEventSampleProperty", typeof(DeviceEventEventArgs)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionDeviceEventSampleProperty", typeof(DeviceEventEventArgs))]
        public string SampleProperty { get; set; }
		
			}
    /// <summary>
    /// Generic Server Event
    /// </summary>
    [GeneratedCode("Driver.Design", "1.0.0.0")]
    [Serializable]
    public partial class ServerEventEventArgs : GeospatialAwareEventEventArgs
    {
        internal ServerEventEventArgs(IDevice device)
            :  base(device)         {           
        }

		internal ServerEventEventArgs(IDevice device, DateTime date)
             :  base(device, date)         {           
        }

        // -- properties
		
		/// <summary>
        /// Sample Property
        /// </summary>
		[CategoryPropertiesAttribute]
        [DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameServerEventSampleProperty", typeof(ServerEventEventArgs)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionServerEventSampleProperty", typeof(ServerEventEventArgs))]
        public string SampleProperty { get; set; }
		
			}
    /// <summary>
    /// Alarm Track Recieved
    /// </summary>
    [GeneratedCode("Driver.Design", "1.0.0.0")]
    [Serializable]
    public partial class AlarmTrackRecievedEventArgs : GeospatialAwareEventEventArgs
    {
        internal AlarmTrackRecievedEventArgs(IDevice device)
            :  base(device)         {           
        }

		internal AlarmTrackRecievedEventArgs(IDevice device, DateTime date)
             :  base(device, date)         {           
        }

        // -- properties
		
		/// <summary>
        /// Track Id
        /// </summary>
		[CategoryPropertiesAttribute]
        [DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameAlarmTrackRecievedTrackId", typeof(AlarmTrackRecievedEventArgs)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionAlarmTrackRecievedTrackId", typeof(AlarmTrackRecievedEventArgs))]
        public string TrackId { get; set; }
		
		/// <summary>
        /// Object Category
        /// </summary>
		[CategoryPropertiesAttribute]
        [DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameAlarmTrackRecievedObjectCategory", typeof(AlarmTrackRecievedEventArgs)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionAlarmTrackRecievedObjectCategory", typeof(AlarmTrackRecievedEventArgs))]
        public string ObjectCategory { get; set; }
		
		/// <summary>
        /// Confidence
        /// </summary>
		[CategoryPropertiesAttribute]
        [DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameAlarmTrackRecievedConfidence", typeof(AlarmTrackRecievedEventArgs)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionAlarmTrackRecievedConfidence", typeof(AlarmTrackRecievedEventArgs))]
        public string Confidence { get; set; }
		
		/// <summary>
        /// Longitude
        /// </summary>
		[CategoryPropertiesAttribute]
        [DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameAlarmTrackRecievedLongitude", typeof(AlarmTrackRecievedEventArgs)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionAlarmTrackRecievedLongitude", typeof(AlarmTrackRecievedEventArgs))]
        public double Longitude { get; set; }
		
		/// <summary>
        /// Bearing
        /// </summary>
		[CategoryPropertiesAttribute]
        [DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameAlarmTrackRecievedBearing", typeof(AlarmTrackRecievedEventArgs)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionAlarmTrackRecievedBearing", typeof(AlarmTrackRecievedEventArgs))]
        public int Bearing { get; set; }
		
		/// <summary>
        /// Velocity
        /// </summary>
		[CategoryPropertiesAttribute]
        [DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameAlarmTrackRecievedVelocity", typeof(AlarmTrackRecievedEventArgs)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionAlarmTrackRecievedVelocity", typeof(AlarmTrackRecievedEventArgs))]
        public int Velocity { get; set; }
		
		/// <summary>
        /// Intial Alarm Date Time
        /// </summary>
		[CategoryPropertiesAttribute]
        [DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameAlarmTrackRecievedIntialAlarmDateTime", typeof(AlarmTrackRecievedEventArgs)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionAlarmTrackRecievedIntialAlarmDateTime", typeof(AlarmTrackRecievedEventArgs))]
        public DateTime IntialAlarmDateTime { get; set; }
		
			}
    /// <summary>
    /// Track Update
    /// </summary>
    [GeneratedCode("Driver.Design", "1.0.0.0")]
    [Serializable]
    public partial class TrackUpdateEventArgs : GeospatialAwareEventEventArgs
    {
        internal TrackUpdateEventArgs(IDevice device)
            :  base(device)         {           
        }

		internal TrackUpdateEventArgs(IDevice device, DateTime date)
             :  base(device, date)         {           
        }

        // -- properties
		
		/// <summary>
        /// Altitude
        /// </summary>
		[CategoryPropertiesAttribute]
        [DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameTrackUpdateAltitude", typeof(TrackUpdateEventArgs)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionTrackUpdateAltitude", typeof(TrackUpdateEventArgs))]
        public  double Altitude { get; set; }
		
		/// <summary>
        /// Velocity
        /// </summary>
		[CategoryPropertiesAttribute]
        [DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameTrackUpdateVelocity", typeof(TrackUpdateEventArgs)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionTrackUpdateVelocity", typeof(TrackUpdateEventArgs))]
        public int Velocity { get; set; }
		
		/// <summary>
        /// Bearing
        /// </summary>
		[CategoryPropertiesAttribute]
        [DisplayName("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DisplayNameTrackUpdateBearing", typeof(TrackUpdateEventArgs)),
        Description("Evbg.CC.Driver.SpotterGlobal.Radar.Design.driverdesign.Strings", "DescriptionTrackUpdateBearing", typeof(TrackUpdateEventArgs))]
        public int Bearing { get; set; }
		
			}
}